# Generated by Django 3.2.13 on 2022-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('chocolate', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(max_length=250)),
            ],
        ),
    ]
